services:
  - type: web
    name: health-risk-ai
    runtime: python
    plan: free
    buildCommand: "pip install --upgrade pip && pip install --no-cache-dir -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.6
      - key: SECRET_KEY
        generateValue: true
      - key: GEMINI_API_KEY
        sync: false
